name: manual jobs

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: demo
        required: true
        type: string
        default: "dev"

jobs:
  demo-inpts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo branch
        uses: actions/checkout@v7

      - name: print values inputs
        run: |
          echo "env: ${{ github.event.inputs.enviroment }}"
  
