name: manual jobs

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: demo
        required: true
        type: string
        default: "dev"

      allow-run:
        description: allow to run steps
        required: true
        type: boolean
        default: true

      data_env:
        description: allow to run steps
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod
          - int
        default: dev 

jobs:
  demo-inpts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo branch
        uses: actions/checkout@v7

      - name: print values inputs
        run: |
          echo "env: ${{ github.event.inputs.enviroment }}"

      - name: allow-run true
        if: ${{ github.event.inputs.allow-run == true }}
        run:
          echo "Build started"

      - name: demp choice inputs
        run: |
          echo "my data env is ${{ github.event.inputs.data_env }}"
